CREATE DATABASE todos_db;

CREATE TABLE users (id SERIAL PRIMARY KEY NOT NULL, name VARCHAR(30), api_key TEXT);

CREATE TABLE todos (id SERIAL PRIMARY KEY NOT NULL, owner_id INTEGER REFERENCES users(id), task TEXT UNIQUE, done BOOLEAN, date_achievement TIMESTAMP NOT NULL DEFAULT NOW());